PROG = pot

C_SRC =  \
	$(SDKDIR)/platform/Device/SiliconLabs/EFM32GG11B/Source/system_efm32gg11b.c \
	$(SDKDIR)/platform/emlib/src/em_adc.c \
	$(SDKDIR)/platform/emlib/src/em_assert.c \
	$(SDKDIR)/platform/emlib/src/em_cmu.c \
	$(SDKDIR)/platform/emlib/src/em_gpio.c \
	./pot.c

S_SRC =  \
	$(SDKDIR)/platform/Device/SiliconLabs/EFM32GG11B/Source/GCC/startup_efm32gg11b.S

include ../gg11.prog.mk
