PROG = hello

C_SRC =  \
	$(SDKDIR)/platform/Device/SiliconLabs/EFM32GG11B/Source/system_efm32gg11b.c \
	$(SDKDIR)/platform/emlib/src/em_assert.c \
	./hello.c

S_SRC =  \
	$(SDKDIR)/platform/Device/SiliconLabs/EFM32GG11B/Source/GCC/startup_efm32gg11b.S

include ../gg11.prog.mk
